### PR TITLE
Code improvements to File upload component

### LINKED ISSUE #5689: Refactor JavaScript initialisation for easier maintainability
## What

Refactor the initialisation of the JavaScript component to help maintainability in the future

## Why

There's a lot happening in the component's constructor, which could gain at being broken down in smaller functions so it's easier to update in the future

## Who needs to work on this

Developers

**Note** Good opportunity for pairing.

## Who needs to review this

Developers

## Done when

- [ ] We spend 1/2 - 1 day improving the component's initialisation code

### LINKED ISSUE #6951: `classes` option not working on new File upload component
## Description of the issue

The `classes` Nunjucks macro option doesn't work with the new improved File upload component. It adds the classes to the hidden input and not to the visible button.

## Steps to reproduce the issue

Add a class to the `classes` option.

## Actual vs expected behaviour

What happens is that those classes are not on the new component.
What is expected to happen is that they should be on the new component.

### PR DESCRIPTION
**Pull request by querkmachine**
Small code improvements and refactoring. Closes #5689.

 ## Changes

- Split the component's constructor into some smaller, discrete functions responsible for generating HTML and binding dragging events. 
- Renamed the `.govuk-drop-zone` element to `.govuk-file-upload-wrapper`.
  - We feel this better describes what the element does, as all of the drop zone styles and functionality are contained on the nested button element and not this one. 
  - To avoid a breaking change, CSS styles are still present for the `.govuk-drop-zone` class so that it still renders correctly without any changes to HTML. JS functionality has not needed to be updated for this change as it did not reference the element by its class name. 
- Added `wrapperClasses` parameter, to add custom classes to the enhanced file upload's wrapper. This could resolve #6951. 
- Added `wrapperAttributes` parameter to add custom HTML attributes to the enhanced file upload's wrapper. This could resolve alphagov/govuk-design-system#5231. 
- Fixed setting of `hidden` HTML attribute to `true` on `<input>` element. 
  - Strictly speaking, the only valid attributes for the HTML `hidden` attribute are "hidden" and "until-found". A value of "true" still works for backwards compatibility with when the attribute was a boolean toggle, but it could be flagged as not being to spec. 
  - Updated the associated test to use the `isVisible` helper. 
- Removed setting `tabindex` and `aria-hidden` on the `<input>` element.
  - Hiding the input with the `hidden` HTML attribute already removes the element from the tab order and accessibility tree, making these redundant.
- Added/updated the types of some of the elements in JS to be more specific. 

## Thoughts

The `wrapperClasses` and `wrapperAttributes` parameters are applied via Nunjucks, which means they're always present even if the enhanced features don't initialise (JS errors, is blocked, etc.) This feels like it might be unexpected, but I'm not sure of a tidier way we could pass a list of attributes through `data-*` and have them applied by JS instead. This might be something better explained in the Nunjucks macro guidance. 

There are no tests for supporting the old `.govuk-drop-zone` class, as I'm unsure of how we would write these.

An issue about devising a way to pass attributes through to JS has been spun off into #6966.

### CODE REVIEW

**Comment by colinrotherham** [comment]
Is it worth moving `data-module="govuk-file-upload"` from the drop zone to the form group wrapper?

It meets the expected separation of what's the component versus what's the child input

Then it'll be consistent with all other JavaScript components that have `govuk-form-group` wrappers. For example, Character Count, Checkboxes, Radios and Password Input

We did this [over in NHS.UK frontend in a backwards-compatible way](https://github.com/nhsuk/nhsuk-frontend/blob/v10.4.2/packages/nhsuk-frontend/src/nhsuk/components/file-upload/file-upload.mjs#L88-L95) to locate the drop zone:

```js
// Locate or create the file drop zone
this.$dropZone = this.$root.classList.contains(dropZoneClass)
  ? this.$root
  : document.createElement('div')

if (this.$root !== this.$dropZone) {
  this.$dropZone.classList.add(dropZoneClass)
}
```

**Comment by querkmachine** [comment]
@colinrotherham Was funnily enough just discussing something like this in Slack: moving the `data-module` definition and having the drop zone be generated in JS rather than being in Nunjucks. I'd quite like to do that, given the messy feeling of having the drop zone be there when it cannot function.

One sticking point to doing that is how we would pass the `dropZoneAttributes` Nunjucks parameter through in a way that JavaScript can pick it up and apply them to the generated element. I don't recall us doing that elsewhere in Frontend and sticking a blob of JSON into a data-* attribute feels like an easy way to create invalid HTML that's also difficult to use outside of the Nunjucks macro.

**Comment by colinrotherham** [comment]
Ah brilliant

Would you then find that `formGroup.attributes` and `formGroup.classes` did the job instead? You might not even need `dropZoneAttributes` and `dropZoneClasses` now that the module is at form-group level

Fully agree that blobs of JSON are a bit sketchy

But we extended the GOV.UK Frontend config system to support arrays if helpful?

* https://github.com/nhsuk/nhsuk-frontend/pull/1747

**Comment by querkmachine** [comment]
@colinrotherham My assumption is that we want the attributes to be placed on the `govuk-drop-zone` element specifically, so that events against it can be captured if they're for analytics, for example.

**Comment by colinrotherham** [comment]
I suppose, at the very least, it gives you a stable component wrapper from which to configure and create the drop zone from 🤷‍♂️

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs [hunk 1]
```diff
@@ -96,7 +96,7 @@ export class FileUpload extends ConfigurableComponent {
     this.$input.id = `${this.id}-input`
 
     // Hide the native input
-    this.$input.setAttribute('hidden', 'true')
+    this.$input.setAttribute('hidden', 'hidden')
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs:99]: To match how you set boolean attributes in other components:

```suggestion
    this.$input.setAttribute('hidden', '')
```

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js [hunk 2]
```diff
@@ -76,12 +76,12 @@ describe('/components/file-upload', () => {
...
-          it('sets tabindex to -1', async () => {
-            const inputElementTabindex = await page.$eval(inputSelector, (el) =>
-              el.getAttribute('tabindex')
+          it('gets hidden', async () => {
+            const inputElementHidden = await page.$eval(inputSelector, (el) =>
+              el.getAttribute('hidden')
             )
 
-            expect(inputElementTabindex).toBe('-1')
+            expect(inputElementHidden).toBe('hidden')
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js]: Don't forget about the [`getProperty()`](https://github.com/colinrotherham/govuk-frontend/commit/7a5faff3d6f1a23196739e1026a92861bd1e75e3) and [`getAttribute()` helpers](https://github.com/alphagov/govuk-frontend/pull/2906/changes/492d07a102d50cd408d734c392ee343fed8ae68b)

```suggestion
            const $input = await page.$(inputSelector)
            expect(await getProperty($input, 'hidden')).toBe(true)
```

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs (hunk 1 above)
Comment (querkmachine) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs:99]: Although this achieves the same end goal, I don't mind being explicit in this case, as hidden isn't a pure boolean attribute anymore: the value could also be `"until-found"`!

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js (hunk 2 above)
Comment (querkmachine) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.puppeteer.test.js]: Or even better for this situation, the `isVisible` helper. 👀
Thanks for the heads up.

**Review by owenatgov — APPROVED** [review]
Giving this a thumbs up. It's a shame about the ts stuff being a barrier to breaking down the constructor more. That would be good to do eventually. This is still a worthwhile improvement.

Are you up for making an issue about conventions for passing config to js-generated markup? I couldn't find one that exists already. Feels like something worth exploring down the line.

**Comment by querkmachine** [comment]
@owenatgov I'll write something up 👍

File: packages/govuk-frontend/src/govuk/components/file-upload/template.njk [hunk 3]
```diff
@@ -73,6 +73,7 @@
       key: 'left-drop-zone',
       message: params.leftDropZoneText
     }) -}}
+    {{- govukAttributes(params.dropZoneAttributes) }}
   >
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/file-upload/template.njk:77]: Just need to avoid a dangling `>` here 🙏

```suggestion
    {{- govukAttributes(params.dropZoneAttributes) }}>
```

Comment (querkmachine) [reply packages/govuk-frontend/src/govuk/components/file-upload/template.njk:77]: It looks like Nunjucks' whitespace control characters are already preventing it being output on a new line when rendered. Is this just for tidiness of the Nunjucks itself?

Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/file-upload/template.njk:77]: Good to know if so

But no, just spotted it was different here versus other `>`

**Review by owenatgov — APPROVED** [review]
Yippeeeeeee we resolved the ts stuff!

**Comment by selfthinker** [comment]
We've just had a wildcard meeting with the squad to discuss a) if there is a need to have the attributes on the button itself to make some types of attributes work and b) if there is a need to have the attributes on the surrounding div (which is what this PR does).

We've decided that we will not want to have the attributes on either of the elements, so would like to remove `dropZoneAttributes` from this PR. I'll put the reasoning for this into the original issue (https://github.com/alphagov/govuk-design-system/issues/5231).

**Comment by selfthinker** [comment]
I personally find the name `dropZoneClasses` misleading as they have nothing to do with the dropzone.
I get that the `div`'s class is "govuk-drop-zone", although I think that is misleading as well and should ideally be changed (which would be a breaking change, so not something I suggest should be done in this PR).

I won't die on that hill, so happy with it as it is.
But we should consider giving it a more sensible name, like `containerClasses`.

**Comment by querkmachine** [comment]
We're now having a bit of back-and-forth on whether we actually want to remove `dropZoneAttributes` (or whatever name it might take), as the ability to add attributes may still be useful for analytics and testing reasons, even if they aren't applied directly to the `<button>` element.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml [hunk 4]
```diff
@@ -104,11 +104,19 @@ params:
...
+    description: Classes to add to the file upload `<input>` element.
   - name: attributes
     type: object
     required: false
-    description: HTML attributes (for example data attributes) to add to the file upload component.
+    description: HTML attributes (for example data attributes) to add to the file upload  `<input>` element.
+  - name: dropZoneClasses
+    type: string
+    required: false
+    description: Classes to add to the enhanced file upload component. If `javascript` is not provided, this option will be ignored.
```
Comment (selfthinker) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: > If `javascript` is not provided, this option will be ignored.

Is that correct? Reading the code and your PR description:

> The `dropZoneClasses` and `dropZoneAttributes` parameters are applied via Nunjucks, which means they're always present even if the enhanced features don't initialise (JS errors, is blocked, etc.)

This would be solved by just renaming them (for example to `containerClasses` and `containerAttributes`). In that case it's fine if they are always applied.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml [hunk 5]
```diff
@@ -104,11 +104,19 @@ params:
...
+  - name: dropZoneAttributes
+    type: object
+    required: false
+    description: HTML attributes (for example data attributes) to add to the enhanced file upload component. If `javascript` is not provided, this option will be ignored.
```
Comment (selfthinker) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: Same here. I don't think that option will be ignored?

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml (hunk 4 above)
Comment (selfthinker) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: Also, we refer to this version of the component in the guidance as the "improved file upload component". Although I think "enhanced" sounds better, we should change it to be consistent.

Comment (querkmachine) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: There's an annoying to describe difference at play here. 

If the `javascript` Nunjucks parameter is not set or false, the HTML element that `dropZoneClasses` and `dropZoneAttributes` are applied to is never output, so those parameters do not work. 

If the `javascript` parameter is true, that element is output and those parameters work, but this happens independently of if the JavaScript parts of the component load or run, so there is a failure state where the drop zone element is present but does not work.

Comment (selfthinker) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: Aaah, sorry, I thought the div would always be there. My bad.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml [hunk 6]
```diff
@@ -104,11 +104,19 @@ params:
   - name: classes
     type: string
     required: false
-    description: Classes to add to the file upload component.
+    description: Classes to add to the file upload `<input>` element.
```
Comment (selfthinker) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: I'd suggest to add the following to this description:

> If `javascript` is provided, these are not copied to the visible button. To use classes for the visible button, use the `dropZoneClasses` option.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml [hunk 7]
```diff
@@ -104,11 +104,19 @@ params:
...
   - name: attributes
     type: object
     required: false
-    description: HTML attributes (for example data attributes) to add to the file upload component.
+    description: HTML attributes (for example data attributes) to add to the file upload  `<input>` element.
```
Comment (selfthinker) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: I'd suggest to add the following to this description:

> If `javascript` is provided, these are not copied to the visible button. To add attributes to the container, use the `dropZoneAttributes` option instead.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml (hunk 4 above)
Comment (selfthinker) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: I will resolve this but re-open a new comment for the "improved" vs "enhanced" as I think that now gets lost in the discussion here.

Comment (selfthinker) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: We refer to this version of the component in the guidance as the "improved file upload component". Although I think "enhanced" sounds better, we should change it to be consistent.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml (hunk 5 above)
Comment (selfthinker) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: Ignore the above per the discussion in the other thread.

But we should change "enhanced" to "improved" to stay consistent with how we're calling the component in the guidance.

File: packages/govuk-frontend/src/govuk/components/file-upload/template.njk [hunk 8]
```diff
@@ -47,7 +47,7 @@
 {% endif %}
 {% if params.javascript %}
   <div
-    class="govuk-drop-zone"
+    class="govuk-file-upload__wrapper {%- if params.wrapperClasses %} {{ params.wrapperClasses }}{% endif %}"
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/file-upload/template.njk]: Wouldn't BEM make `govuk-file-upload__wrapper` a child of `govuk-file-upload`?

Where `govuk-file-upload` would be the component (or block level)

From this issue: https://github.com/alphagov/govuk-frontend/issues/3071

Comment (querkmachine) [reply packages/govuk-frontend/src/govuk/components/file-upload/template.njk]: Yup, but this is precisely so that the naming is consistent with the wonky BEM in use on other components that conditionally add wrapping elements (like Text input) 😅

Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/file-upload/template.njk]: Doubling up the selectors is a good idea, but maybe un-wonky the input instead of making file upload more wonky to match? 😆

```patch
+ .govuk-input-wrapper,
+ 
+ // @deprecated .govuk-input__wrapper class is deprecated in favour of .govuk-input-wrapper
  .govuk-input__wrapper {
```

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml [hunk 9]
```diff
@@ -179,6 +187,18 @@ examples:
...
       multiple: true
 
+  - name: enhanced, custom classes and attributes
+    options:
+      javascript: true
+      id: file-upload-3
+      name: file-upload-3
+      label:
+        text: Upload files
+      wrapperClasses: app-drop-zone--custom-class
```
Comment (owenatgov) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.yaml]: **Nitpick**: since we've renamed drop zone to wrapper, should this follow suit?


```suggestion
      wrapperClasses: app-file-upload-wrapper--custom-class
```

File: packages/govuk-frontend/src/govuk/components/file-upload/template.test.js [hunk 10]
```diff
@@ -220,23 +220,46 @@ describe('File upload', () => {
     it('adds the data-module attribute to the wrapper when `true`', () => {
       const $ = render('file-upload', examples.enhanced)
 
-      const $wrapper = $('.govuk-form-group > .govuk-drop-zone')
+      const $wrapper = $('.govuk-form-group > .govuk-file-upload-wrapper')
 
       expect($wrapper.attr('data-module')).toBe('govuk-file-upload')
     })
 
+    it('renders custom drop zone classes', () => {
```
Comment (owenatgov) [inline packages/govuk-frontend/src/govuk/components/file-upload/template.test.js]: Similar nitpick about terminology

```suggestion
    it('renders custom wrapper classes', () => {
```

File: packages/govuk-frontend/src/govuk/components/file-upload/template.test.js [hunk 11]
```diff
@@ -220,23 +220,46 @@ describe('File upload', () => {
...
+      const $ = render(
+        'file-upload',
+        examples['enhanced, custom classes and attributes']
+      )
+
+      const $wrapper = $('.govuk-form-group > .govuk-file-upload-wrapper')
+
+      expect($wrapper.hasClass('app-drop-zone--custom-class')).toBeTruthy()
```
Comment (owenatgov) [inline packages/govuk-frontend/src/govuk/components/file-upload/template.test.js]: This would need updating depending on if you take on my comment in the yaml or not

File: packages/govuk-frontend/src/govuk/components/file-upload/template.test.js [hunk 12]
```diff
@@ -220,23 +220,46 @@ describe('File upload', () => {
...
+    })
+
+    it('renders custom drop zone attributes', () => {
```
Comment (owenatgov) [inline packages/govuk-frontend/src/govuk/components/file-upload/template.test.js]: Similar nitpick on terminology

```suggestion
    it('renders custom wrapper attributes', () => {
```

**Review by owenatgov — APPROVED** [review]
Looks great. I have a couple of comments about terminology across our testing which are far from blockers to getting this merged. Take on or ignore at your discretion.

Could you also please raise an issue to remove `govuk-drop-zone` and attach it to the v7 milestone. Separately we also probably want an issue to either remove the file upload enhanced feature flag or to _decide_ if we want to remove it, also attached to the v7 milestone.
