### PR TITLE
Throw error when instantiating components where GOV.UK Frontend is not supported

### LINKED ISSUE #4009: Throw errors if GOV.UK Frontend is not supported
## What

Throw a `GOVUKFrontendNotSupportedError` (extending a base `GOVUKFrontendError`) if any of our JavaScript component is instanciated while GOV.UK Frontend is not supported (`document.body.classList.contains('govuk-frontend-supported')`).

> **Note**: Components throwing because of this means we'll likely want an early return in `initAll` to avoid riddling the console with exceptions logs

## Why

This avoids users getting a reference to a component in an invalid state, as well as helps debugging with a clear error (rather than nothing happening).

You can find more information about this decision in [our decision record](https://github.com/alphagov/govuk-design-system-architecture/pull/32/files).

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] All components throw an error if instanciated where GOV.UK Frontend is not supported

### PR DESCRIPTION
**Pull request by romaricpascal**
This PR updates all our JavaScript components to throw a `GOVUKFrontendNotSupportedError` if they get instantiated where GOV.UK Frontend is not supported.

Besides updating the components to throw this new error the PR:

- introduces a `GOVUKFrontendError` for our errors to subclass. It allows users to easily [separate our custom errors from regular JavaScript errors using `instanceof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#handling_a_specific_error_type).
- updates `renderAndInitialise` to make running code before the component's initialisation more reliable (had issues where the `initialiser` – now renamed `beforeInitialisation` for clarity – didn't execute when run in the middle of the block instantiating the component).

Closes #4009

### CODE REVIEW

File: packages/govuk-frontend/src/govuk/all.mjs [hunk 1]
```diff
@@ -103,6 +104,7 @@ export {
   Checkboxes,
   ErrorSummary,
   ExitThisPage,
+  GOVUKFrontendError,
```
Comment (romaricpascal) [inline packages/govuk-frontend/src/govuk/all.mjs:107]: Only export our base `GOVUKFrontendError` rather than all error classes with the aim of:

- allowing separating our own errors from native ones in bulk, which users can do running `instanceof GOVUKFrontendError`
- but not crowding our export with each error we throw, as users can check the type of error through [their `name` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name)

File: packages/govuk-frontend/src/govuk/errors/index.mjs [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+ *   // set a new `name` on the subclass. The `name` property is important
+ *   // to ensure intelligible error names even if the class name gets
+ *   // mangled by a minifier
+ *   name = "MissingRootError"
+ * }
+ * ```
+ * @abstract
+ */
+export class GOVUKFrontendError extends Error {
+  name = 'GOVUKFrontendError'
```
Comment (romaricpascal) [inline packages/govuk-frontend/src/govuk/errors/index.mjs:20]: Annoying, but necessary. Simply extending `Error` doesn't give the error a new name, unfortunately. 

And going for something automated like `this.name = this.constructor.name` in `GOVUKFrontendError`'s `constructor` means the error gets a mangled name once minifier have run over the code and rename the class to say `n`. While we may prevent the mangling in our files, we don't control how services minify theirs, so hardcoding the name limits risks of having an error with the name of `n`.

File: docs/contributing/coding-standards/js.md [hunk 3]
```diff
@@ -133,6 +133,40 @@ Avoid using namespace imports (`import * as namespace`) in code bundled for Comm
 
 Prefer named exports over default exports to avoid compatibility issues with transpiler "synthetic default" as discussed in: https://github.com/alphagov/govuk-frontend/issues/2829
 
+## Throwing errors
```
Comment (romaricpascal) [inline docs/contributing/coding-standards/js.md:136]: This is just a starter for 10 listing the spirit in which the errors have been implemented in this PR. Happy to discuss and update.

File: packages/govuk-frontend/src/govuk/all.mjs (hunk 1 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/all.mjs:107]: Fab work in this PR Romaric

Do we want to discuss if we're ready for errors to be part of our "public" API?

Bit like the **I18n** class, we chose not to export it

(Gives us freedom to keep iterating without breaking changes)

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs [hunk 4]
```diff
@@ -113,7 +114,11 @@ export class Accordion {
    * @param {AccordionConfig} [config] - Accordion config
    */
   constructor ($module, config) {
-    if (!($module instanceof HTMLElement) || !document.body.classList.contains('govuk-frontend-supported')) {
+    if (!document.body.classList.contains('govuk-frontend-supported')) {
+      throw new GOVUKFrontendNotSupportedError()
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:118]: Just a random thought

Similar to how `TypeError` isn't `NotCorrectTypeError`, should we flip out the `Not`?

```suggestion
      throw new GOVUKFrontendSupportError()
```

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js [hunk 5]
```diff
@@ -508,6 +508,28 @@ describe('/components/accordion', () => {
...
+          beforeAll(async () => {
+            examples = await getExamples('accordion')
+          })
+
+          it('throws when GOV.UK Frontend is not supported', async () => {
+            await expect(
+              renderAndInitialise(page, 'accordion', {
+                params: examples.default,
+                beforeInitialisation () {
+                  document.body.classList.remove('govuk-frontend-supported')
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/accordion/accordion.test.js:524]: 🎉

File: packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js [hunk 6]
```diff
@@ -648,7 +670,7 @@ describe('Character count', () => {
           // Override maxlength to 10
           maxlength: 10
         },
-        initialiser ($module) {
+        beforeInitialisation ($module) {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/character-count/character-count.test.js:673]: As it's no longer with us, as a sign of respect for `.init()` shall we rename this? 😆

Suppose it matches `initAll()` a bit better too

```suggestion
        beforeInit ($module) {
```

File: packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs [hunk 7]
```diff
@@ -22,14 +23,11 @@ export class ErrorSummary {
    * @param {ErrorSummaryConfig} [config] - Error summary config
    */
   constructor ($module, config) {
-    // Some consuming code may not be passing a module,
-    // for example if they initialise the component
-    // on their own by directly passing the result
-    // of `document.querySelector`.
-    // To avoid breaking further JavaScript initialisation
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs:29]: I was quite fond of this message, all on its own in **ErrorSummary**

Thoughts on adding a little disclaimer to every component?

1. Error throws
2. Error console shows stack trace
3. Stack trace uses original source via source maps
4. Developer clicks to these lines and reads helpful message

File: packages/govuk-frontend/src/govuk/components/globals.test.js [hunk 8]
```diff
@@ -37,6 +37,7 @@ describe('GOV.UK Frontend', () => {
         'Checkboxes',
         'ErrorSummary',
         'ExitThisPage',
+        'GOVUKFrontendError',
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/globals.test.js:40]: Related to https://github.com/alphagov/govuk-frontend/pull/4030/files#r1284215663

Should we not export our errors in the default export, we'll need to manage Terser mangling:

https://github.com/alphagov/govuk-frontend/blob/91d0a5d8b694875b34eb4be52ecf155f8b3701d0/packages/govuk-frontend/rollup.release.config.mjs#L31-L33

File: packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js [hunk 9]
```diff
@@ -1,165 +1,219 @@
...
   let examples
 
   beforeAll(async () => {
     examples = await getExamples('notification-banner')
   })
 
-  it('has the correct tabindex attribute to be focused with JavaScript', async () => {
-    await goToComponent(page, 'notification-banner', {
-      exampleName: 'with-type-as-success'
+  describe('when type is set to "success"', () => {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js:11]: Nice little test refactor with the `describe()` nesting, mind if we split it into another commit?

File: packages/govuk-frontend/src/govuk/components/radios/radios.test.js [hunk 10]
```diff
@@ -1,236 +1,261 @@
...
+const { goToComponent, goToExample, getProperty, getAttribute, isVisible, renderAndInitialise } = require('govuk-frontend-helpers/puppeteer')
+const { getExamples } = require('govuk-frontend-lib/files.js')
 
-describe('Radios with conditional reveals', () => {
-  describe('when JavaScript is unavailable or fails', () => {
-    beforeAll(async () => {
-      await page.setJavaScriptEnabled(false)
-    })
+describe('Radios', () => {
+  describe('with conditional reveals', () => {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/radios/radios.test.js:5]: Same with this one, separate commit?

Jest output is improved too ⭐

File: packages/govuk-frontend/src/govuk/errors/index.mjs [hunk 11]
```diff
@@ -0,0 +1,33 @@
+/**
+ * A base class for `Error`s thrown by GOV.UK Frontend.
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/errors/index.mjs:2]: Mind if we keep a short and sweet "title" at the top for any generated docs?

```suggestion
 * GOV.UK Frontend error
 *
 * A base class for errors thrown by GOV.UK Frontend.
```

File: packages/govuk-frontend/src/govuk/errors/index.mjs [hunk 12]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ * It is meant to be extended into specific types of errors
+ * to be thrown by our code.
+ *
+ * @example
+ * ```js
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/errors/index.mjs:8]: Just a reminder to use `mjs` over `js` for ES modules code blocks

Can't remember if ESLint is set up for these (like it is for Markdown) but it might matter one day

File: packages/govuk-frontend/src/govuk/errors/index.mjs [hunk 13]
```diff
@@ -0,0 +1,33 @@
...
+  name = 'GOVUKFrontendError'
+}
+
+/**
+ * Indicates that GOV.UK Frontend is not supported
+ */
+export class GOVUKFrontendNotSupportedError extends GOVUKFrontendError {
+  name = 'GOVUKFrontendNotSupportedError'
+
+  /** */
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/errors/index.mjs:29]:
```suggestion
```

File: shared/helpers/puppeteer.js [hunk 14]
```diff
@@ -91,19 +90,42 @@ async function renderAndInitialise (page, componentName, options) {
...
+    await page.$eval('[data-module]', options.beforeInitialisation)
+  }
+
   // Run a script to init the JavaScript component
-  await page.evaluate(async (exportName, options) => {
+  //
+  // Use `evaluate` to ensure we run `document.querySelector` inside the
+  // browser, like users would, rather than rely on Puppeteer looking for the
+  // element which would cause an error in Jest-land rather than within the
+  // browser if the element is missingß
```
Comment (colinrotherham) [inline shared/helpers/puppeteer.js:105]:
```suggestion
  // browser if the element is missing
```

File: shared/helpers/puppeteer.js [hunk 15]
```diff
@@ -91,19 +90,42 @@ async function renderAndInitialise (page, componentName, options) {
...
-
     const namespace = await import('govuk-frontend')
-    /* eslint-disable-next-line no-new */
-    new namespace[exportName]($module, options.config)
+
+    try {
+      /* eslint-disable-next-line no-new */
+      new namespace[exportName]($module, options.config)
+    } catch ({ name, message }) {
+      return { name, message }
```
Comment (colinrotherham) [inline shared/helpers/puppeteer.js:121]: So even if we re-throw (not return) on this line it doesn't work? 😣

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs (hunk 4 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:118]: Fair, and that makes it shorter, I'll rename 😊

File: packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs (hunk 7 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/error-summary/error-summary.mjs:29]: I think most of that info should be summarised in the error message when implementing `https://github.com/alphagov/govuk-frontend/issues/4035`.

Regarding adding things to each components, I think this would rather be the role of a base Component class. I think with the error throwing for GOV.UK Frontend support and the type check of `$module` there's enough ground for creating it already (only to add new features to it, not refactor existing code into it) and centralise these checks and possible comments.

File: packages/govuk-frontend/src/govuk/components/globals.test.js (hunk 8 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/globals.test.js:40]: Can you expand on what we'll need to manage on the Terser side if we don't export the errors internally? 

If it's about the error naming after mangling, [the hardcoded `name` property is there to handle the situation](https://github.com/alphagov/govuk-frontend/pull/4030#discussion_r1280921668) (especially as we can't guarantee that library users will take the same step as us towards not mangling the name of the errors/our exports).

File: packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js (hunk 9 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/notification-banner/notification-banner.test.js:11]: No probs, I'll split the extra `describe`s in their own commit to separate them from the implementation of the error throwing.

File: shared/helpers/puppeteer.js (hunk 15 above)
Comment (romaricpascal) [reply shared/helpers/puppeteer.js:121]: Indeed, the information was still lost when re-throwing 😣 I didn't think of checking what lands in the `pageerror` event, though so I'll give that a quick go if it can avoid us that juggling.

File: packages/govuk-frontend/src/govuk/errors/index.mjs (hunk 12 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/errors/index.mjs:8]: The example doesn't use anything module specific (`import`/`export`) so plain `js` is fine there 😊 

Regarding ESLint, it doesn't seem we've enabled [jsdoc/check-examples](https://github.com/gajus/eslint-plugin-jsdoc/blob/HEAD/docs/rules/check-examples.md#readme). We can discuss its enabling in a separate part as it may have some tricky side effects (eg. requiring this class to have its own JSDoc block inside the example).

File: shared/helpers/puppeteer.js (hunk 15 above)
Comment (romaricpascal) [reply shared/helpers/puppeteer.js:121]: No more luck looking at the `pageerror` and `error` events on the page. If I remove the `try/catch` in the code that's run by `page.evaluate`, no event gets triggered. The promise for `page.evaluate` simply rejects, with only a `name` property to the mangled class name of the error (see the following Jest output) 😞 

```diff
- Object {
-   "message": "GOV.UK Frontend is not supported in this browser",
-   "name": "GOVUKFrontendNotSupportedError",
+ Error {
+   "name": "n",
}
```

File: packages/govuk-frontend/src/govuk/errors/index.mjs [hunk 16]
```diff
@@ -0,0 +1,33 @@
...
+ * ```js
+ * class MissingRootError extends GOVUKFrontendError {
+ *   // Setting an explicit name is important as extending the class will not
+ *   // set a new `name` on the subclass. The `name` property is important
+ *   // to ensure intelligible error names even if the class name gets
+ *   // mangled by a minifier
+ *   name = "MissingRootError"
+ * }
+ * ```
+ * @abstract
```
[the remark this answers is not in the document]
Comment (36degrees) [reply packages/govuk-frontend/src/govuk/errors/index.mjs:17]: Worth enforcing this in the constructor too?

```js
export class GOVUKFrontendError extends Error {
  name = 'GOVUKFrontendError'

  constructor () {
    if (this.constructor == GOVUKFrontendError) {
      throw new Error("GOVUKFrontendError is an abstract class and can't be instantiated");
    }
  }
}
```

Or is errors throwing errors too confusing?

File: shared/helpers/puppeteer.js (hunk 15 above)
Comment (romaricpascal) [reply shared/helpers/puppeteer.js:121]: What's weird is that puppeteer on its own seems to be happy with errors that have a custom name thrown from `page.evaluate`.

Taking the following script:

```mjs
import puppeteer from 'puppeteer';

// Launch the browser and open a new blank page
const browser = await puppeteer.launch({
  headless: 'new'
});
const page = await browser.newPage();

await page.goto('about:blank')

try {
  await page.evaluate(() => {
    class CustomError extends Error {
      name = 'CustomError'
    }

    throw new CustomError('Custom message in custom error')
  })
} catch (error) {
  console.log('Error class:', error.constructor.name)
  const {name, message, cause } = error
  console.log('Contents:', {name, message, cause})
  console.log(error)
}
```

The logs end up as expected (the class on the Node side can only be `Error` as the `CustomError` only exists inside the browser's page).

```sh
Error class: Error
Contents: {
  name: 'CustomError',
  message: 'Custom message in custom error',
  cause: undefined
}
Error [CustomError]: Custom message in custom error
```

So there's something in between that messes with our `page.evaluate` and requires us to add that workaround with `throw`.

I had a quick look in the sources of argos-ci/jest-puppeteer (especially jest-environment-puppeteer), but didn't notice anything that would wrap `page.evaluate` to mess with the error thrown. The page seems to be a regular Puppeteer page 😔

Comment (colinrotherham) [reply shared/helpers/puppeteer.js:121]: Is the name-shortening to `n` [from Terser](https://github.com/alphagov/govuk-frontend/pull/4030#discussion_r1284234033)?

File: packages/govuk-frontend/src/govuk/components/globals.test.js (hunk 8 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/globals.test.js:40]: Yeah that `mangle.reserved` option

But if the mangled error class name doesn't appear in stack traces then all good

File: shared/helpers/puppeteer.js (hunk 15 above)
Comment (romaricpascal) [reply shared/helpers/puppeteer.js:121]: Yup, that's what ends up in the `govuk-frontend.min.js` that's being built in `dist` and then loaded by the review app 😊

File: packages/govuk-frontend/src/govuk/errors/index.mjs (hunk 12 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/errors/index.mjs:8]: Yeah not so much the module specific stuff

We tend to use [`*.mjs` as the default now](https://github.com/alphagov/govuk-frontend/commit/4f6a747ce3b25e7a5323b772fd4ca47a8049780b), so some rules like the TypeScript parser are only for `*.mjs`

https://github.com/alphagov/govuk-frontend/blob/e1ef6d2df52908e1b87a8c692bc894adf015f57c/packages/govuk-frontend/.eslintrc.js#L11-L13

File: packages/govuk-frontend/src/govuk/errors/index.mjs (hunk 13 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/errors/index.mjs:29]: Oh, no, that wasn't whoops, it's making ESLint happy as there's not much to document on that constructor 🤔 I'll replace with a more explicit disabling of ESLint for that line 😊

**Comment by romaricpascal** [comment]
Deleted comments were from the dist diff action, which I had triggered by mistakenly commiting a test build of `dist` 🤦🏻 

@colinrotherham I think I've addressed all the code bits of your feedback (discussions on which bits of the errors are public API to be had). I've also added an extra commit to refactor the validation into a central class as we know that's the architecture we're going towards, so there's not much sense spreading new features all across the components when we can already have them centralised from the get go 😊 I'll try centralising the testing tomorrow so hold your review for a bit please (though the class is tested via all the class inherinting... really wish we could gather coverage in the browser 😔 )

File: packages/govuk-frontend/src/govuk/component.mjs [hunk 17]
```diff
@@ -0,0 +1,31 @@
...
+
+/**
+ * Base Component class
+ *
+ * Centralises the behaviours shared by our components
+ *
+ * @internal
+ * @abstract
+ */
+export class Component {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/component.mjs:11]: 🎉

File: packages/govuk-frontend/src/govuk/component.mjs [hunk 18]
```diff
@@ -0,0 +1,31 @@
...
+  /**
+   * Constructs a new component, validating that GOV.UK Frontend is supported
+   *
+   * @internal
+   */
+  constructor () {
+    this.validateGOVUKFrontendSupport()
```
Comment (romaricpascal) [inline packages/govuk-frontend/src/govuk/component.mjs:18]: Idea is to keep that constructor a series of method calls to give an easy overview of what's happening. It'll also allow fine grained overriding should someone need to reach to the internals to amend one of these behaviours 😊

Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/component.mjs:18]: Probably pair a shorter `checkSupport()` with an `isSupported` getter?

Based on our current method names:

```
checkMode()
checkIfAllSectionsOpen()
checkForSessionStorage()
```

Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/component.mjs:18]: Just seen your comment, holding off!

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/component.mjs:18]: Sounds fine with me, I'll update tomorrow.

Regarding `isSupported()`, I'd be keen to have it as a utility function in `govuk/common/index.mjs` rather than on the class itself as there's no `this` involved in its execution.

File: packages/govuk-frontend/src/govuk/common/index.mjs [hunk 19]
```diff
@@ -133,3 +133,17 @@ export function extractConfigByNamespace(configObject, namespace) {
...
+ *
+ * Some pages may be able to load our JavaScript, but GOV.UK Frontend may not be
+ * supported due to our check relying on support for `nomodule` rather than
+ * `type="module"` (as we can't detect the latter)
+ *
+ * @internal
+ * @returns {boolean} Whether GOV.UK Frontend is supported on this page
+ */
+export function isSupported() {
+  return document.body.classList.contains('govuk-frontend-supported')
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/common/index.mjs:148]: Possibly want to pass in `document` as a parameter here?

For use in Puppeteer helpers or Cheerio tests where `document` might not be global

Did something similar in Design System's [`new Navigation(document)`](https://github.com/alphagov/govuk-design-system/blob/e8224f2f1bbd4dae82c11b73b71495a07c120d93/src/javascripts/components/navigation.mjs#L8-L14)

**Comment by romaricpascal** [comment]
> I'll try centralising the testing tomorrow so hold your review for a bit please (though the class is tested via all the class inherinting... really wish we could gather coverage in the browser 😔 )

So... centralising a test for `Component` would actually require that class to be exported. Otherwise, it can't be accessed in the scripts that run in the browser to be exercised. Until we make it part of our public API, we'll have to exercise it through the components that extend it. I think that's fine though, as we do need to test these components anyways.

I think it's good for review now @colinrotherham 😊

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs [hunk 20]
```diff
@@ -14,7 +15,7 @@ import { I18n } from '../../i18n.mjs'
  * The state of each section is saved to the DOM via the `aria-expanded`
  * attribute, which also provides accessibility.
  */
-export class Accordion {
+export class Accordion extends Component {
```
[the remark this answers is not in the document]
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:18]: Oh, that's not something I had considered too much, just went with what felt right. `GOVUKComponent` feels very verbose, as well as misnamed (I'd think a `GOVUKComponent` would be part of the GOV.UK project). `GOVUKFrontendComponent` even more verbose. I'd be keen to keep `Component` for shortness.

For the `Error`, though, I think a little verbosity is useful to avoid confusion of what `throw new Error()` does (is it ours or a native error). If we shorten to `Error`, people would have to `import {Error as GOVUKFrontendError} from 'govuk-frontend'` to make their code clear, so we may as well take that step already 😊

[the remark this answers is not in the document]
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:18]: Feels strange having two approaches

How about `BaseError` and `BaseComponent`?

File: packages/govuk-frontend/src/govuk/errors/index.mjs (hunk 16 above)
[the remark this answers is not in the document]
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/errors/index.mjs:19]: I'm not sure it's worth enforcing the `@abstract` in code. I'd rather lean towards shipping less code and if we get evidence that people misuse it, clamp down on it rather than be pre-emptively defensive 😊

File: packages/govuk-frontend/src/govuk/common/index.mjs (hunk 19 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/common/index.mjs:147]: Ohhh, good spot. Missed a unit test for this method, which will require passing JSDom's document 😊 I'll add a `$scope` argument defaulted to `document.body` (to avoid people having to set it themselves).

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs (hunk 20 above)
[the remark this answers is not in the document]
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:18]: I think it's important the error gets prefixed with `GOVUKFrontend`. It makes `instanceof` checks clearer: `instanceof GOVUKFrontendError` is more explicit than `instanceof BaseError`. This prefix would hopefully also make people think twice before extending it for their own purposes: we'd want them to throw their own kind of error if possible so there's a separation between service errors and our own library errors.

For the component bit, I think on the contrary it's important that its not labelled `GOVUKFrontend`. Down the road, we're imagining encouraging people to extend it. Creating `GOVUKFrontendComponent`s reads like creating "components of GOVUKFrontend", while it'd be just `Components` for their service.

As we haven't released yet, we can still tweak namings. Would you be fine moving naming discussion in its own issue while we implement the other errors? 😊

File: packages/govuk-frontend/src/govuk/all.mjs (hunk 1 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/all.mjs:117]: Let's default to not exporting it yet, can always add it in another PR

File: packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs (hunk 20 above)
[the remark this answers is not in the document]
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/accordion/accordion.mjs:18]: Quick Slack decision?

Your point is great for `instanceof GOVUKFrontendComponent` too

File: packages/govuk-frontend/src/govuk/common/index.mjs [hunk 21]
```diff
@@ -133,3 +133,17 @@ export function extractConfigByNamespace(configObject, namespace) {
...
+ * Checks if GOV.UK Frontend is supported on this page
+ *
+ * Some browsers will load and run our JavaScript but GOV.UK Frontend
+ * won't be supported.
+ *
+ * @internal
+ * @param {HTMLElement} [$scope] - The `<body>` element of the document to check for support
+ * @returns {boolean} Whether GOV.UK Frontend is supported on this page
+ */
+export function isSupported($scope = document.body) {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/common/index.mjs:147]: Do we have browser support for parameter defaults without Babel polyfills?

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/common/index.mjs:147]: Yup, Babel leaves that line as is in `dist`. Support looks [a bit older than what we're configured to support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#browser_compatibility). And if transpilation happened, there's [no polyfills involved](https://babeljs.io/repl#?browsers=IE%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABDAzgZRAB03ATlAUwBMAKAEhQjkwMQF5Ei4IQBbAsKAOgCM4iAngEpEAbwBQiRLgJQQuJBSo0uEADYBDFCgAyqblU4aYYFCQDkAczgA3EAGsAtMFwJCYIo5RYc-YuaEAbnEAXyA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.22.10&externalPlugins=&assumptions=%7B%7D). So all good there 🎉

**Review by colinrotherham — APPROVED** [review]

File: packages/govuk-frontend/src/govuk/components/globals.test.js (hunk 8 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/globals.test.js]: Added a comment about mangling on this PR: https://github.com/alphagov/govuk-frontend/pull/4075.

The name is clear in the logged message, but mangled in the stacktrace. I think mangling is worth its own discussion, as it may be worth disabling it altogether rather than keep maintaining an evergrowing list of names to not mangle for our `min.js` file.

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/globals.test.js]: And opened https://github.com/alphagov/govuk-frontend/issues/4076 to explore our options.
