### PR TITLE
Fix functionality of enhanced File Upload when no CSS

### LINKED ISSUE #5688: Investigate if we can hide the `<input>` and handle drop on the `<button>` when CSS is disabled
## What

Investigate if the `<input>` can be hidden when CSS is not available (through the `hidden` attribute) and drops on the button, which mentions 'or drop file', can be handled as well.

That last part may require us to fill the `<input>` using the data in the `drop` event rather than letting users drop on an invisible `<input>`. If we do so, we'll want to dispatch a `change` [`CustomEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) so other parts of the page can respond to the field being filled (`CustomEvent` allowing to differentiate our event from a native event if necessary).

## Why

At the moment, the drop feature works by letting users drop on the `<input>` itself. This relies on CSS to position the `<input>` over the `<button>` and make it invisble. If CSS fails to load or is tweaked by a custom stylesheet:
- the `<input>` remains visible, cluttering the page
- the `<button>` presents that you can drop files, but it won't fill the input

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] We spent 1/2 - 1 day investigating if we can hide the input and drop on the button when CSS is not loading.

### PR DESCRIPTION
**Pull request by patrickpatrickpatrick**
## What

- `input` element hidden during File Upload enhancement initialisation
- `button` listens for drop event and updates status and input accordingly

## Why

Fixes #5688

### CODE REVIEW

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs [hunk 1]
```diff
@@ -144,6 +145,10 @@ export class FileUpload extends ConfigurableComponent {
       `${$label.id} ${commaSpan.id} ${$button.id}`
     )
     $button.addEventListener('click', this.onClick.bind(this))
+    $button.addEventListener('dragover', (event) => {
+      // prevent default to allow drop
+      event.preventDefault()
+    })
```
Comment (romaricpascal) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs:151]: **suggestion** This would be best regrouped with the `drop` handler as they're related to the same feature. Looks like quite a few of the event handlers are further down near the `drop` handler, so this and the `click` handler could be both moved down.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs [hunk 2]
```diff
@@ -157,6 +162,18 @@ export class FileUpload extends ConfigurableComponent {
...
     this.$status = $status
 
+    // if there is no CSS and input is hidden
+    // button will need to handle drop event
+    this.$button.addEventListener('drop', (event) => {
+      event.preventDefault()
+
+      if (event.dataTransfer && isContainingFiles(event.dataTransfer)) {
+        this.$input.files = event.dataTransfer.files
+        this.onDrop()
```
Comment (romaricpascal) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs:172]: **issue** As the `<input>` is fully `hidden`, no `drop` will ever happen to it, so the existing `onDrop` method can be repurposed to handle the `drop` on the `<button>`. This should allow to simplify it as it won't need to listen to the `change` event, to something like the following:

```js
  onDrop() {
		event.preventDefault()

      if (event.dataTransfer && isContainingFiles(event.dataTransfer)) {
        this.$input.files = event.dataTransfer.files

				// Dispatch a `change` event so external code that would rely on the `<input>`
				// dispatching an event when files are dropped still work.
 			// Use a `CustomEvent` so our events are distinguishable from browser's native events 
				this.$input.dispatchEvent(new CustomEvent('change'))
				
				this.$announcements.innerText = this.$status.innerText
   		this.hideDraggingState()
     }
  }
```

We can also remove the `this.$input.addEventListener('drop',...)` line 198.

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs:172]: And I think we can clean up the CSS that absolutely positions the `<input>` while dragging as well, as it's completely `hidden`, which means we can potentially clean up the JavaScript that sets the `--enhanced` and `--dragging` modifiers on that element.

**Review by romaricpascal — COMMENTED** [review]
Nice! Makes the screen much tidier when CSS is not available and the drop feature works nicely. 🙌🏻 

https://github.com/user-attachments/assets/ec6fae63-d419-47fa-8848-7a9dff15161c

Just needs a little tidy up enabled by the `<input>` being `hidden` in HTML now. I've proposed a few bits which I think can be removed/regrouped, if they don't work let me know. And if you see anything else that could be removed because we're fully hiding the `<input>`, let's remove it as well.

**Review by romaricpascal — APPROVED** [review]
All good to go, thanks for the tidy up! ⛵
