### PR TITLE
Throw errors during Tabs initialisation if key HTML elements are missing

### LINKED ISSUE #4127: Throw errors during Tabs initialisation if key HTML elements are missing
## What

Update our JavaScript components requiring specific HTML elements to be present so they throw a `MissingElementError` (extending `GOVUKFrontendError`) rather than silently fail:

- The tabs (`<a>`)
- The tablist and their items
- The tab panel associated to a tab

## Why

This is part of our work to [have our components throw rather than silently return during initialisation](https://github.com/alphagov/govuk-design-system-architecture/blob/main/decision-records/009-throw-errors-component-constructors.md).

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Component has been updated to throw errors

### PR DESCRIPTION
**Pull request by domoscargin**
Closes #4127 

A coupla notes:

- So far, I've limited this PR to replacing empty returns in the initialisation of the component. There are 17 more empty returns in the component, some of which are bound during initialisation. These are in event handlers, however, which we can refactor as and when we add things to the API.
- I've removed a check in `setup()` as unnecessary. Some checks will need to replace it if `setup()` becomes an API method that can be called separately from initialisation, but I figure we'd probably do a slight code refactor then anyway.

### CODE REVIEW

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs [hunk 1]
```diff
@@ -53,7 +53,10 @@ export class Tabs extends GOVUKFrontendComponent {
     /** @satisfies {NodeListOf<HTMLAnchorElement>} */
     const $tabs = $module.querySelectorAll('a.govuk-tabs__tab')
     if (!$tabs.length) {
-      return this
+      throw new ElementError(null, {
+        componentName: 'Tabs',
+        identifier: 'a.govuk-tabs__tab'
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:58]: Wondering if we need to show this _scoped_ via `$module` as it's not from `document` here?

```suggestion
        identifier: `[data-module="${Tabs.moduleName}"] a.govuk-tabs__tab`
```

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs [hunk 2]
```diff
@@ -64,6 +67,28 @@ export class Tabs extends GOVUKFrontendComponent {
...
+
+    if (!$tabListItems.length) {
+      throw new ElementError(null, {
+        componentName: 'Tabs',
+        identifier: '.govuk-tabs__list-item'
+      })
+    }
+
+    this.$tabList = $tabList
+    this.$tabListItems = $tabListItems
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:90]: Love it, thanks @domoscargin

If you can add them as class fields too?

```mjs
  /** @private */
  $tabs

  /** @private */
  $tabList

  /** @private */
  $tabListItems
```

Won't need types as they can be inferred in the constructor

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs [hunk 3]
```diff
@@ -107,18 +136,9 @@ export class Tabs extends GOVUKFrontendComponent {
    * @private
    */
   setup() {
-    const $tabList = this.$module.querySelector('.govuk-tabs__list')
-    const $tabListItems = this.$module.querySelectorAll(
-      '.govuk-tabs__list-item'
-    )
-
-    if (!this.$tabs || !$tabList || !$tabListItems) {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:115]: 🙌

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs (hunk 1 above)
Comment (domoscargin) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: Went with the first one since we've been doing it that way so far, but we can always revisit when we review these.

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs (hunk 2 above)
Comment (domoscargin) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:96]: Donezos

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs (hunk 1 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: I asked @romaricpascal the same question on this thread here: https://github.com/alphagov/govuk-frontend/pull/4261#discussion_r1337169400

Will leave you two to decide what's best

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: I think going for the `scope` thing will require quite a bit of investigation so I'd prefer we only look at it if needs arise.

Regarding the addition of `[data-module="${Tabs.moduleName}"]`, which new information does it bring in addition to:
- the name of the component that starts the error messages
- our classnames which usually refer to the component as well

Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: It came up [whilst discussing Checkboxes](https://github.com/alphagov/govuk-frontend/pull/4236#discussion_r1331778120) since realising it's only **Error summary**, **Radios**, **Checkboxes** and **Exit this page** that use `document.querySelector()` versus `$module.querySelector()` etc

So wondered if we should explain that or not, or undo previous scoping as part of https://github.com/alphagov/govuk-frontend/issues/4072

E.g. In previous PRs we've [scoped via `$module.hash target #${linkedElementId}`](https://github.com/alphagov/govuk-frontend/commit/fd7a8ed7e10d0dc8f4a362f0e7482839d0a43534#diff-fb3a25d42cbb3621d375cc34dc960447e84fa2a8729fd16e97e4c34edd9b17aeR66)

Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: Let's see once we have the whole list of errors for #4072. That'll give us a clear view of which component parts are referenced. And we can decide on which extra prefix we may need to better locate the faulty element on top of the name of the component that couldn't initialise.

Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: So drop the prefix in this PR like you've done in https://github.com/alphagov/govuk-frontend/pull/4261?

**Review by colinrotherham — COMMENTED** [review]
This is looking ace @domoscargin

Just merged https://github.com/alphagov/govuk-frontend/pull/4261 so let's give this one a rebase and [drop the `[data-module="${Tabs.moduleName}"]` prefix](https://github.com/alphagov/govuk-frontend/pull/4263#discussion_r1337536858) then think we're good to go 🚀

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs [hunk 4]
```diff
@@ -64,6 +73,28 @@ export class Tabs extends GOVUKFrontendComponent {
     this.boundTabKeydown = this.onTabKeydown.bind(this)
     this.boundOnHashChange = this.onHashChange.bind(this)
 
+    const $tabList = this.$module.querySelector('.govuk-tabs__list')
+    const $tabListItems = this.$module.querySelectorAll(
+      'li.govuk-tabs__list-item'
+    )
+
+    if (!$tabList) {
+      throw new ElementError($tabList, {
```
Comment (colinrotherham) [inline packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:82]: Sorry, this old chestnut again 😆

```suggestion
      throw new ElementError(null, {
```

**Review by colinrotherham — APPROVED** [review]
✅ Approved

(One little comment, but only a quick tweak)

File: packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs (hunk 4 above)
Comment (colinrotherham) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs:82]: Not caused by this PR, but should really match up the JSDoc at the other end

i.e. Adding `| null` to the allowed types

```mjs
/**
 * @param {Element | null} element - The element in error
 */
```

Comment (domoscargin) [reply packages/govuk-frontend/src/govuk/components/tabs/tabs.mjs]: Implemented the suggestion and add `| null` to the ElementError JSDoc.
