### PR TITLE
Account for `multiple` attribute when enhancing a File Input

### LINKED ISSUE #5791: Enhanced file upload allows dropping multiple files even when HTML input is set to only accept a single file
## Description of the issue

Enhanced version of the file upload allows to drop multiple files even when the HTML input is set to only accept a single file

## Steps to reproduce the issue

When a file input is set to only accept a single file

``<input id="question-file-field" class="govuk-file-upload" aria-describedby="question-file-hint" accept="text/csv, image/jpeg, image/png, application/rtf, text/plain, application/pdf, application/json, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.oasis.opendocument.text" type="file" name="question[file]"> ``

The user can still drop multiple files into the file upload area. 

https://github.com/user-attachments/assets/c477fba0-3213-47b2-9a23-b174539bcad3

## Actual vs expected behaviour

This behaviour is unexpected and it should only be allowed if the file upload input has specified `multiple` attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#multiple

The expected behaviour is that user will not be able to drop multiple files onto the field that does not have 'multiple' attribute.

The impact of the unexpected behaviour is that if a file upload can only accept one file, and user drops multiple files, and they can view that multiple files were chosen, when they proceed to upload the file with a 'Continue' button, then the system only uploads one of the files, which can confuse users.

The native file browser selector behaves as expected and only allows for selecting one file.

## Environment (where applicable)

- Operating system:  macOS Sequoia 15.3.2
- Browser: Chrome
- Browser version: 134.0.6998.89 (Official Build) (arm64)
- GOV.UK Frontend Version: the latest 😉

### PR DESCRIPTION
**Pull request by romaricpascal**
Updates the checks done when dragging and dropping over the enhanced file upload attribute to account for the presence of the `multiple` attribute on the enhanced `<input>`. When absent, the enhanced file upload will only accept drops of a single file. The component will also check the number of files being dragged when it can (more on that right after) to decide whether to change state when the user drags over it.

Handling the `drop` event and the `dragenter` event need to be done slightly differently.

During the `drop`, the `files` property of the event's [`dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) contains the list of files so we can just count that before allowing to copy into the input's `files` property. That's the easy part.

Before the `drop`, when deciding to change state or not:
- the `files` property is not filled (that'd be a bit creepy if any webpage had access to the files content when you passed over it while dragging 😬 
- the event's `dataTransfer` offers an`items` property with more limited information, but a useful [`kind` property](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem#instance_properties) for each item, set to `file` when the item is a file. [It isn't filled in by Safari](https://github.com/mdn/browser-compat-data/issues/24898), but as Chrome and Firefox provide it we can use it if present to count the items whose `kind` is `file` (at the cost of a good old `for` loop as [`DataTransferItemList`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList) is not an array or iterable)
- in the absence of `items`, we at least have a list of the types of things being dragged inside the `dataTransfer`'s `types` property, which we can check for the presence of a `Files`
- except we've seen it missing at times in Safari, so if we have no information, we'll assume users can drop and let the `drop` event take care of deciding whether the input can be filled or not

### Implementation considerations

The implementation adds two new methods to the component: `canFillInput` at the point of `drop` and `canDrop` for before that. Those are currently private could be offered for extension in the future, allowing teams to implement further logic for accepting or rejecting files (for example meeting the criteria of the `accept` attribute) with something like the following untested code:

```js
class AppFileInput extends FileInput {
   canDrop(dataTransfer) {
   	return super(dataTransfer) && dataTransfer.items.length && accepts(dataTransfer.items)
   }
   
   canFillInput(dataTransfer) {
   	return super(dataTransfer) && accepts(dataTransfer.files)
   }
   
   accepts(itemsOrFiles) {
	 for (let i = 0; i < itemsOrFiles.length; i++) {
		if (!this.isAcceptableType(itemsOrFiles[i].type)) {
			return false;
		}
	 }
     return true;
   } 
}
```

Fixes #5791

### CODE REVIEW

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs [hunk 1]
```diff
@@ -303,6 +303,58 @@ export class FileUpload extends ConfigurableComponent {
     }
   }
 
+  /**
+   * Confirms if enhanced `<input>` can be filed with files from the given `DataTransfer`
```
Comment (domoscargin) [inline packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs]:
```suggestion
   * Confirms if enhanced `<input>` can be filled with files from the given `DataTransfer`
```

**Review by domoscargin — APPROVED** [review]
I think this seems good and the behaviour seems as expected when I play around on the review app.

File: packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs (hunk 1 above)
Comment (romaricpascal) [reply packages/govuk-frontend/src/govuk/components/file-upload/file-upload.mjs]: Whoops, let me correct that before merging! Thanks for the review 🙌🏻
