### PR TITLE
Fix `global-builtin` deprecation in test code

### LINKED ISSUE #6163: Sass has deprecated global functions that exist in sass:modules (`global-builtin`)
### Cause

Dart Sass (the primary Sass implementation) has [deprecated using global functions that exist in sass:modules](https://sass-lang.com/documentation/breaking-changes/import/) since v1.80.0. Instead we should use the appropriate sass module.

For example, `map.has-key` rather than `map-key`.

We have chosen to use the global functions because in order to use the functions from `sass:modules` we'd need to `@use` them, which would break support for LibSass and Ruby Sass which we still support.

### Consequences

Currently, the only side effect of this change is a few deprecation warnings being produced when govuk-frontend is compiled with Sass >= 1.78.0. We currently silence these warnings within our own tooling.

These global functions won't be removed until Dart Sass 3.0, seemingly with the exception of the color functions which are deprecated separately – see #6147.

### Impact of debt

Low

### Reason (impact of debt)

The warnings are annoying, but [they can be silenced](https://frontend.design-system.service.gov.uk/import-css/#override-with-your-own-css) by our users.

### Effort to pay down

Low

### Reason (effort to pay down)

Once we've dropped support for LibSass and Ruby Sass, fixing the deprecations is trivial.

We may be able to use the [Sass migration tool](https://sass-lang.com/documentation/breaking-changes/import/#automatic-migration) to do it automatically.

### Overall rating

Low

### Reason (overall rating)

This has little impact on users today (other than needing to silence deprecations coming from dependencies), and fixing the issue will be trivial once we've dropped support for LibSass and Ruby Sass.

### PR DESCRIPTION
**Pull request by romaricpascal**
Some of our tests were using Sass global functions rather than `@use`ing them from the relevant module. Those were missed in #6731, so this PR remediates to that by:

- adding `global-builtin` to the list of [`fatalDeprecations`](https://sass-lang.com/documentation/js-api/interfaces/options/#fatalDeprecations) so we have better visibility
- fixing the failures for each function call

Because we cannot update the code of `sass-color-helpers` used to do contrast computations for the organisational colours, the PR uses `quietDeps` in that tests to silence the deprecations. A future removal of the library is planned in #6737

Fixes #6163

### CODE REVIEW

File: shared/config/sass.js [hunk 1]
```diff
@@ -2,7 +2,8 @@
  * @type {import('sass-embedded').Options<"async">}
  */
 const deprecationOptions = {
-  silenceDeprecations: ['import', 'mixed-decls']
+  silenceDeprecations: ['import', 'mixed-decls'],
+  fatalDeprecations: ['global-builtin']
```
Comment (romaricpascal) [inline shared/config/sass.js:6]: **note** Was hoping we could use `Version.parse(1.79.0)` to trigger any deprecation from 1.79 and under. However, this is not compatible with `mixed-decls` being silenced 😢

Comment (36degrees) [reply shared/config/sass.js:6]: I think I still have a stash of changes where I import all deprecations from sass, filter out the silenced ones, and set all other deprecations as fatal.

I abandoned it when I realised we already had a test that failed on warnings, but happy to dig it out if you think it'd be useful.
